### ISSUE TITLE
Using this in a packaged chrome app gives me an error because of an usafe eval.

### ISSUE THREAD

**Issue by ncri** [AceMetrix/jquery-deparam#10]
Can we get rid of it? 

    var global = (false || eval)('this');

**Comment by badunk** [comment]
I read up on this and found this: http://perfectionkills.com/unnecessarily-comprehensive-look-into-a-rather-insignificant-issue-of-global-objects-creation/

Towards the end, there is a snippet there about referencing `this` to refer to global/window is not possible in strict mode.

**Comment by ncri** [comment]
What about dsturley's commit? I simply use this in my app (i don't use strict mode). But would be great if this was solved in master.
