### ISSUE TITLE
invalid-meta and invalid version in bower.json

### ISSUE THREAD

**Issue by nharraud** [AceMetrix/jquery-deparam#14]
bower.json version is 0.3.0 even though it is published as 0.4.2 on bower. `bower install` is complaining about this: `mismatch Version declared in the json (0.3.0) is different than the resolved one (0.4.2)`

There is also another error during `bower install`: `invalid-meta jquery-deparam is missing "ignore" entry in bower.json`

**Comment by badunk** [comment]
thanks
