### ISSUE TITLE
Remove reliance on jQuery

### ISSUE THREAD

**Issue by patsissons** [AceMetrix/jquery-deparam#17]
This would be fantastic if it didn't have a reliance on jQuery. I'm not sure if you have thought about this aspect before. If you're not too interested in doing something like that I may be able to get the work done this weekend and create a PR.

**Comment by badunk** [comment]
I think I would prefer if it was conditionally reliant on jQuery, maybe officially an optionalDependency in node.

I have removed any absolute requirements on jQuery in the past by removing any jQuery utility functions, but I suppose it still attempts to put itself within jQuery's namespace.

It would be nice to detect and do that if jquery is available, but ultimately stay standalone if not.

I've love a PR :)

**Comment by patsissons** [comment]
sounds good i'll see what i can do this weekend.
